FROM python:3.9.13

RUN \
    apt-get update &&\
    apt-get -y install \
        libpq-dev \
        python3-dev
ENV PYTHONUNBUFFERED=0
ENV PYTHONUSERBASE=/usr/local/
ENV PATH=${PYTHONUSERBASE}lib/python3.9/site-packages/bin:${PATH}

WORKDIR /app

ADD compose/django/start-dev.sh /start-dev.sh

RUN chmod +x /*.sh