# Generated by Django 4.0.6 on 2022-08-12 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('address', models.CharField(blank=True, max_length=100)),
                ('type', models.IntegerField(choices=[(1, '초등학교'), (2, '중학교'), (3, '고등학교')], default=3)),
                ('edu_office_code', models.CharField(choices=[('B10', '서울특별시교육청'), ('C10', '부산광역시교육청'), ('D10', '대구광역시교육청'), ('E10', '인천광역시교육청'), ('F10', '광주광역시교육청'), ('G10', '대전광역시교육청'), ('H10', '울산광역시교육청'), ('I10', '세종특별자치시교육청'), ('J10', '경기도교육청'), ('K10', '강원도교육청'), ('M10', '충청북도교육청'), ('N10', '충청남도교육청'), ('P10', '전라북도교육청'), ('Q10', '전라남도교육청'), ('R10', '경상북도교육청'), ('S10', '경상남도교육청'), ('T10', '제주특별자치도교육청'), ('V10', '재외한국학교교육청')], default='B10', max_length=10)),
            ],
        ),
    ]
