# Generated by Django 4.0.6 on 2022-08-22 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0002_menu_date_school_idx_menu_unique_school_type_date'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='menu',
            name='date_school_idx',
        ),
        migrations.AddIndex(
            model_name='menu',
            index=models.Index(fields=['school', 'date'], name='school_date_idx'),
        ),
    ]
